using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RDLLVL
{
    public class Objects
    {
        public Dictionary<uint, string> ObjectList = new Dictionary<uint, string>()
        {
            {0, "Door" },
            {1, "Falling Background Object" },
            {2, "Guide Sign" },
            {3, "Locked Shutter Door" },
            {4, "Pop Flower" },
            {5, "Start Point" },
            {6, "Dimension Hole" },
            {7, "Warp Star" },
            {8, "Arrow Sign" },
            {9, "Stage Select Door" },
            {10, "Rope Platform" },
            {11, "Camera" },
            {12, "Another Dimension Wall" },
            {14, "Wooden Stake" },
            {15, "Blue Switch" },
            {16, "Purple Switch" },
            {17, "Red Switch" },
            {18, "Bomb Block Chain Starter" },
            {19, "Floating Cannon" },
            {20, "Invisibility Stone Gate" },
            {26, "Fuse" },
            {27, "Fuse Cannon" },
            {28, "Statue Block" },
            {29, "Giant Rope" },
            {30, "Shutter Door" },
            {31, "Light Block" },
            {32, "Hang Switch" },
            {34, "Hang Rope" },
            {35, "Flare Beam Switch" },
            {36, "Lor Starcutter" },
            {37, "Magolor" },
            {38, "Lor Starcutter Arrow Sign" },
            {39, "Large Wooden Stake" },
            {40, "Grand Hammer Spring" },
            {41, "Lor Starcutter Monitor" },
            {42, "Pushing Wind" },
            {43, "Challenge Stage Door" },
            {45, "Pushing Bubbles" },
            {46, "Falling Stalagtite" },
            {47, "Spinning Bar Hazard" },
            {48, "Breakable Roof" },
            {51, "Giant Bell" },
            {55, "Sandcastle Block" },
            {57, "Giant Sandcastle Block" },
            {58, "Lor Starcutter Door" },
            {60, "Bite Statue" },
            {61, "Pirate Ship Octopus" },
            {63, "Press Machine" },
            {66, "Strike Box" },
            {68, "Lava Geyser" },
            {70, "Giant Bowling Pin" },
            {71, "Confetti Ball" },
            {72, "Medium Wooden Stake" },
            {74, "Snowman Body" },
            {75, "Multiplayer Start Point" },
            {77, "Circuit End" },
            {78, "Circuit Block" },
            {80, "Injection Box" },
            {82, "Salamander Head" },
            {83, "Salamander Part" },
            {84, "Key Dee" },
            {85, "Sliceable Volcano" },
            {87, "Sliceable Magma Pillar" },
            {88, "Freezing Volcano" },
        };
        public Dictionary<uint, string> SpecialItemList = new Dictionary<uint, string>()
        {
            {0, "Bouncing Ability Star" },
            {1, "Key" },
            {2, "Maxim Tomato Box" },
            {3, "Candle" },
            {4, "Cracker" },
            {5, "Invisibility Stone" },
            {6, "Balloon Bomb" },
            {7, "Stomper Boot" },
            {8, "Prism Shield" },
            {9, "Maxim Tomato Box (Alt)" },
        };
        public Dictionary<uint, string> ItemList = new Dictionary<uint, string>()
        {
            {0, "Point Star" },
            {1, "1-UP" },
            {2, "Maxim Tomato" },
            {3, "Food" },
            {4, "Energy Sphere" },
            {5, "Invincible Candy" },
            {6, "Red Point Star" },
            {7, "Blue Point Star" },
            {8, "Copy Essence" },
            {9, "Challenge Coin" },
            {10, "Maxim Tomato (Alt)" },
            {11, "Lor Part" },
            {12, "Super Ability Star" },
            {13, "Energy Sphere (Red Point Star)" },
            {14, "Energy Sphere (Empty)" },
        };
        public Dictionary<uint, string> BossList = new Dictionary<uint, string>()
        {
            {0, "Sphere Doomer" },
            {1, "Whispy Woods" },
            {2, "Gigant Edge" },
            {3, "Mr. Dooter" },
            {4, "Water Galboros" },
            {5, "King Doo" },
            {6, "Kibble Blade" },
            {7, "Bonkers" },
            {8, "Dubior" },
            {9, "Grand Doomer" },
            {10, "Moundo" },
            {11, "HR-D3" },
            {12, "Fatty Puffer" },
            {13, "Goriath" },
            {14, "Lor Starcutter" },
            {15, "Magolor" },
            {16, "Landia" },
            {17, "Unknown" },
            {18, "Magolor Soul" },
            {19, "Metal General" },
            {20, "Galacta Knight" },
        };
        public Dictionary<uint, string> EnemyList = new Dictionary<uint, string>()
        {
            {0, "Sir Kibble" },
            {1, "Bronto Burt" },
            {2, "Waddle Dee" },
            {3, "Blade Knight" },
            {4, "Cappy" },
            {5, "Hothead" },
            {6, "Knuckle Joe" },
            {7, "Puppet Dee" },
            {8, "Armor Dee" },
            {9, "Como" },
            {10, "Gordo" },
            {11, "Togekuki" },
            {12, "Whippy" },
            {13, "Pacto" },
            {14, "Shotzo" },
            {15, "Leafan" },
            {16, "Waddle Doo" },
            {17, "Bouncy" },
            {18, "Sparky" },
            {19, "Needlous" },
            {20, "Broom Hatter" },
            {21, "Scarfy" },
            {22, "Nruff" },
            {23, "Flamer" },
            {24, "Tick" },
            {25, "Water Galbo" },
            {26, "Rocky" },
            {27, "Bulby" },
            {28, "Starman" },
            {29, "Twister" },
            {30, "Poppy Bros Jr" },
            {31, "Noddy" },
            {32, "Cerulean" },
            {33, "Blipper" },
            {34, "Gigatzo" },
            {35, "Babut" },
            {36, "Glunk" },
            {37, "Bouncy Sis" },
            {39, "Mumbies" },
            {40, "Parasol Waddle Dee" },
            {41, "Kabu" },
            {42, "Parasol Waddle Doo" },
            {43, "Mopoo" },
            {44, "Foley" },
            {45, "Juckle" },
            {46, "Bowby" },
            {47, "Owgulf" },
            {48, "Degout" },
            {49, "Sheld" },
            {50, "Lanzer" },
            {51, "Chilly" },
            {52, "Moonja" },
            {53, "Pluid" },
            {54, "Gemra" },
            {55, "Wapod Pot" },
            {57, "Volttzo" },
            {58, "Barbar" },
            {59, "Barracu" },
            {60, "Squishy" },
            {61, "Clayn" },
            {62, "Pierce" },
            {63, "Searches" },
            {64, "Walky" },
            {65, "Elec" },
            {66, "Rope Waddle Dee" },
            {67, "Rope Waddle Doo" },
            {68, "Sodory" },
            {69, "Galbo" },
            {70, "Snowl" },
            {72, "Halcandle Dee" },
            {73, "Coldtzo" },
            {74, "Coconut Bomb" },
            {75, "Craby" },
            {76, "Pacloud" },
            {77, "Iron Barbar" },
            {78, "Walf" },
            {81, "Larpa" },
            {82, "Liepa" },
            {83, "Lupa" },
            {84, "Leaper" },
            {85, "Halcandran Bronto Burt" },
            {86, "Halcandran Armor Dee" },
            {87, "Waddle Dee on Nruff" },
            {88, "Hunter Degout" },
            {89, "Hunter Scarfy" },
            {92, "Sandbag" },
            {93, "Parasol Halcandle Dee" },
            {94, "Halcandran Bouncy" },
            {95, "Halcandran Bowby" },
            {96, "Sun" },
            {106, "Whispy Apple" },
            {107, "Poison Whispy Apple" },
            {110, "Mr. Dooter Snake" },
            {115, "Poppy Jr. Bomb" },
            {126, "Fatty Puffer Jr" },
            {129, "Wapod" },
            {145, "Magolor" },
        };

        public Dictionary<uint, string> DecorationList = new Dictionary<uint, string>()
        {
            {1, "Kamitake" },
            {2, "Hasikura" },
            {3, "Morisita" },
            {4, "Noriko" },
            {5, "Cave" },
            {6, "Grass" },
            {7, "Fujiura" },
            {8, "Log" },
            {9, "GCK Beach" },
            {10, "GCK Canyon" },
            {11, "GCK Snow MT" },
            {12, "Lowper" },
            {13, "Desert" },
            {14, "Cave Normal" },
            {15, "Oasis" },
            {16, "Level Map 1" },
            {17, "Air Fort" },
            {18, "Air Island" },
            {19, "Air Temple" },
            {20, "Beach" },
            {21, "Bridge" },
            {22, "Factory" },
            {23, "GCK Cloud" },
            {24, "Hasiguti" },
            {25, "Hondayu" },
            {26, "Ice Building" },
            {27, "Ice Cave" },
            {28, "Lava" },
            {29, "Minami" },
            {30, "Pyramid" },
            {31, "Sea" },
            {32, "Sea Temple" },
            {33, "Snow" },
            {34, "Subway" },
            {35, "Sun" },
            {36, "Volcano" },
            {37, "H_Itoh" },
            {39, "Lowper2" },
            {40, "Level Map 2" },
            {41, "Level Map 3" },
            {42, "Level Map 4" },
            {43, "Level Map 5" },
            {44, "Level Map 6" },
            {45, "Level Map 7" },
            {46, "Challenge" },
            {47, "Ship" },
            {48, "Shooting" },
            {49, "Final" },
            {50, "Challenge 01" },
            {51, "Challenge 02" },
            {52, "Challenge 03" },
            {53, "Challenge 04" },
            {54, "Challenge 05" },
            {55, "Challenge 06" },
            {56, "Challenge 07" },
            {57, "Landia" },
            {58, "GCK Cloud 2" },
            {59, "Desert 2" },
            {60, "Landia 2" },
            {61, "Room" },
            {62, "Room 2" },
            {63, "GCK Canyon 2" },
            {64, "Halcandra" },
            {65, "Air Temple 2" },
            {66, "Empty" },
            {67, "Hex" },
            {68, "Pop Star" },
            {69, "Sea Temple 2" },
            {70, "Blank" }
        };
        public Dictionary<uint, string> FilterList = new Dictionary<uint, string>()
        {
            {0, "Normal" },
            {1, "Darkness" },
            {2, "Grayscale" }
        };
        public Dictionary<uint, string> RunEffectList = new Dictionary<uint, string>()
        {
            {0, "Normal" },
            {1, "Unknown" },
            {2, "VS. Lor Starcutter" },
            {3, "VS. Magolor" },
            {4, "Level Map" },
        };
        public List<string> BGMList = new List<string>()
        {
            "BGM_LP_ARENALOBBY1",
            "BGM_LP_BMACHINE1",
            "BGM_LP_BOSSGNIGHT1",
            "BGM_LP_BOSSMAE1",
            "BGM_LP_BOSSMAE2",
            "BGM_LP_BOSSTYU1",
            "BGM_LP_BOSSTYU2",
            "BGM_LP_BOSSTYUM2",
            "BGM_LP_BOSSWADO1",
            "BGM_LP_BUKIMI1",
            "BGM_LP_CACTUS1",
            "BGM_LP_CANYON1",
            "BGM_LP_CASTLE1",
            "BGM_LP_CAVE1",
            "BGM_LP_COLD1",
            "BGM_LP_COLD2",
            "BGM_LP_COLDWIND1",
            "BGM_LP_COMIC1",
            "BGM_LP_COMIC2",
            "BGM_LP_COMICHAL2",
            "BGM_LP_CONGA1",
            "BGM_LP_CONTINUE1",
            "BGM_LP_CONTINUE2",
            "BGM_LP_CONTINUE3",
            "BGM_LP_DARK1",
            "BGM_LP_DB1",
            "BGM_LP_DEDEDE1",
            "BGM_LP_DEDEDE2",
            "BGM_LP_DEDEDE3",
            "BGM_LP_DEDEDE4",
            "BGM_LP_DESERT1",
            "BGM_LP_FIFTH1",
            "BGM_LP_FISH1",
            "BGM_LP_FUNK1",
            "BGM_LP_GB1",
            "BGM_LP_HALBERD1",
            "BGM_LP_HEITI1",
            "BGM_LP_HEN1",
            "BGM_LP_ICE1",
            "BGM_LP_IWA1",
            "BGM_LP_KAWASAKI1",
            "BGM_LP_KAZAN1",
            "BGM_LP_KIRAKIRA1",
            "BGM_LP_KIRAKIRA2",
            "BGM_LP_KUMO1",
            "BGM_LP_LASTBOSS1",
            "BGM_LP_LASTBOSS2",
            "BGM_LP_LEVEL1",
            "BGM_LP_LEVELBUKIMI1",
            "BGM_LP_LEVELKAZAN1",
            "BGM_LP_LEVELMACHINE1",
            "BGM_LP_LEVELOPEN1",
            "BGM_LP_MACHINE1",
            "BGM_LP_MACHINE2",
            "BGM_LP_MAGMA1",
            "BGM_LP_MENU1",
            "BGM_LP_MINE1",
            "BGM_LP_MINILOOP1",
            "BGM_LP_MINILOOP2",
            "BGM_LP_MINILOOP3",
            "BGM_LP_MINILOOP4",
            "BGM_LP_MORI1",
            "BGM_LP_MUTEKI1",
            "BGM_LP_NORMAL1",
            "BGM_LP_ORCH1",
            "BGM_LP_PLAIN1",
            "BGM_LP_PLANTS1",
            "BGM_LP_RAIN1",
            "BGM_LP_REGG1",
            "BGM_LP_RESULTMENU1",
            "BGM_LP_ROCK1",
            "BGM_LP_ROCKISOGI1",
            "BGM_LP_ROCKISOGINOI1",
            "BGM_LP_ROCKNOI1",
            "BGM_LP_ROOM1",
            "BGM_LP_SAMBA1",
            "BGM_LP_SAWAYAKA1",
            "BGM_LP_SETUNA1",
            "BGM_LP_SETUNA2",
            "BGM_LP_SLOW1",
            "BGM_LP_SUPERNOURYOKU1",
            "BGM_LP_SUPERNOURYOKU2",
            "BGM_LP_TECH1",
            "BGM_LP_TECHNO1",
            "BGM_LP_TOUT1",
            "BGM_LP_TRAINING1",
            "BGM_LP_UMI1",
            "BGM_LP_WADO2",
            "BGM_LP_WADOHAL2",
            "BGM_LP_WATER1",
            "BGM_LP_WATER2",
            "BGM_LP_WORLD1",
            "BGM_LP_YUMEKUMO1",
            "BGM_LP_YUMEKUMOHAL1",
            "BGM_NOLP_BANNER1",
            "BGM_NOLP_CLEAR1",
            "BGM_NOLP_CLEARDANCE1",
            "BGM_NOLP_CLEARDANCEMOVIE2",
            "BGM_NOLP_CLEARSH1",
            "BGM_NOLP_DANCE2NORMAL1",
            "BGM_NOLP_DANMATU1",
            "BGM_NOLP_DANMATU2",
            "BGM_NOLP_DANMATU3",
            "BGM_NOLP_DEAD1",
            "BGM_NOLP_ENDING1",
            "BGM_NOLP_FANF1",
            "BGM_NOLP_FANF2",
            "BGM_NOLP_FANF3",
            "BGM_NOLP_FANF4",
            "BGM_NOLP_FANF5",
            "BGM_NOLP_FANF6",
            "BGM_NOLP_FANF7",
            "BGM_NOLP_FANF8",
            "BGM_NOLP_FANF9",
            "BGM_NOLP_FUNEGATTAI1",
            "BGM_NOLP_FUNEGATTAI2",
            "BGM_NOLP_GAMEOVER1",
            "BGM_NOLP_HARUKANDORAHE1",
            "BGM_NOLP_MAHOROAYABOU1",
            "BGM_NOLP_MOVIEBATTLE1",
            "BGM_NOLP_MOVIEBATTLE2",
            "BGM_NOLP_MOVIEOPENING1",
            "BGM_NOLP_STAFF1",
            "BGM_NOLP_SUPERNOURYOKUEND1"
        };
    }
}
